export const GET_MOVIES = "GET_MOVIES"

export const ADD_NOMINATION = "ADD_NOMINATION"
export const REMOVE_NOMINATION = "REMOVE_NOMINATION"
export const NOMINATION_LIMIT = "NOMINATION_LIMIT"
export const BACK_TO_NORMAL = "BACK_TO_NORMAL"
